### ISSUE TITLE
how to solve the error of AttributeError: 'Tensor' object has no attribute 'isnan'

### ISSUE THREAD

**Issue by xiaosa96** [yuantn/MIAL#2]
hello,
AttributeError: 'Tensor' object has no attribute 'isnan' when I run./script.sh 0.   May I ask how to solve it? My PyTorch environment is 1.5.0, TorchVision environment is 0.6.0, and MMCV version is 1.0.5

**Comment by yuantn** [comment]
Hello,

I have checked the document of PyTorch 1.5.0, and there exists the function " isnan() " in this version ( https://pytorch.org/docs/1.5.0/torch.html?highlight=isnan#torch.isnan ).

I think there are two ways to solve the problem:

1. Re-install the Pytorch and TorchVision with the instructions provided by the PyTorch official website ( https://pytorch.org/get-started/previous-versions/#v160 )

2. Check the lines of AttributeError, and replace the " if value.isnan() " with " if value != value " ( considering that only nan != nan). I think the error may be in the Line 482 and 568 of the " ./mmdet/models/dense_heads/MIAL_head.py ".

**Comment by xiaosa96** [comment]
> > hello,
> > AttributeError: 'Tensor' object has no attribute 'isnan' when I run./script.sh 0. May I ask how to solve it? My PyTorch environment is 1.5.0, TorchVision environment is 0.6.0, and MMCV version is 1.0.5
> 
> Hello,
> 
> I have checked the document of PyTorch 1.5.0, and there exists the function " isnan() " in this version ( https://pytorch.org/docs/1.5.0/torch.html?highlight=isnan#torch.isnan ).
> 
> I think there are two ways to solve the problem:
> 
> 1. Re-install the Pytorch and TorchVision with the instructions provided by the PyTorch official website ( https://pytorch.org/get-started/previous-versions/#v160 )
> 2. Check the lines of AttributeError, and replace the " if value.isnan() " with " if value != value " ( considering that only nan != nan). I think the error may be in the Line 482 and 568 of the " ./mmdet/models/dense_heads/MIAL_head.py ".

您好：
      非常感谢您昨晚给我的回复，目前这个问题通过使用您给的第二个解决方法已经解决了，再次感谢您的回复，谢谢！同时祝您在新的一年多发顶会顶刊，感谢！

**Comment by yuantn** [comment]
> 
> 
> > > hello,
> > > AttributeError: 'Tensor' object has no attribute 'isnan' when I run./script.sh 0. May I ask how to solve it? My PyTorch environment is 1.5.0, TorchVision environment is 0.6.0, and MMCV version is 1.0.5
> > 
> > 
> > Hello,
> > I have checked the document of PyTorch 1.5.0, and there exists the function " isnan() " in this version ( https://pytorch.org/docs/1.5.0/torch.html?highlight=isnan#torch.isnan ).
> > I think there are two ways to solve the problem:
> > 
> > 1. Re-install the Pytorch and TorchVision with the instructions provided by the PyTorch official website ( https://pytorch.org/get-started/previous-versions/#v160 )
> > 2. Check the lines of AttributeError, and replace the " if value.isnan() " with " if value != value " ( considering that only nan != nan). I think the error may be in the Line 482 and 568 of the " ./mmdet/models/dense_heads/MIAL_head.py ".
> 
> 您好：
> 非常感谢您昨晚给我的回复，目前这个问题通过使用您给的第二个解决方法已经解决了，再次感谢您的回复，谢谢！同时祝您在新的一年多发顶会顶刊，感谢！

😄
